sensor:
  - platform: mqtt
    state_topic: "flora/C4:7C:8D:6C:AF:AF/temperature"
    name: "Dragon Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    force_update: true
  - platform: mqtt
    state_topic: "flora/C4:7C:8D:6C:AF:AF/moisture"
    name: "Dragon Moisture"
    unit_of_measurement: "%"
    device_class: humidity
    force_update: true
  - platform: mqtt
    state_topic: "flora/C4:7C:8D:6C:AF:AF/light"
    name: "Dragon Brightness"
    unit_of_measurement: "lux"
    device_class: illuminance
    force_update: true
  - platform: mqtt
    state_topic: "flora/C4:7C:8D:6C:AF:AF/conductivity"
    name: "Dragon Conductivity"
    unit_of_measurement: "uS/cm"
    force_update: true
  - platform: mqtt
    state_topic: "flora/C4:7C:8D:6C:AF:AF/battery"
    name: "Dragon Sensor Battery"
    unit_of_measurement: "%"
    device_class: battery
    force_update: true  
    - platform: mqtt
    state_topic: "flora/80:EA:CA:89:37:DF/boroncharge"
    name: "Particle Boron Charge"
    unit_of_measurement: "%"
    device_class: battery
    force_update: true